# fly.toml app configuration file generated for server-broken-sunset-5881 on 2024-09-30T17:49:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "server-broken-sunset-5881"
primary_region = "ams"

[build]
  dockerfile = "./Dockerfile"  # Assuming you're in the server directory

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1  # Change to at least 1 to ensure the app is always running
  processes = ["app"]

[[services]]
  http_checks = []
  [[services.ports]]
    port = "80"  # HTTP port
  [[services.ports]]
    port = "443" # HTTPS port

